### ISSUE TITLE
Linker Issue and OfxCV

### ISSUE THREAD

**Issue by TobiOmo** [fabiaserra/crea#19]
Sry about this question as i am also very new to this. First issue I got was

when using codeblocks-13.12mingw-setup.exe and followed all the steps you gave, when building the project i got this errors. saying it cant find vmo.h??? then you said i should make sure you have the line #define GESTURE_FOLLOWER commented in ofApp.h. Which i did and that resolved that issue. But then i got another issue which was

ld.exe||cannot find -lstrmbase|
ld.exe||cannot find -lz|

I realized this was a Linker/Compiler related issue, and you advised me to check the following step (e): http://openframeworks.cc/setup/codeblocks/ and check this OF forum entry, they discuss your same error: http://forum.openframeworks.cc/t/error-cannot-find-lstrmbase/3990﻿. I did I uninstalled everything and Installed it again that fixed that issue once i follwed the steps in the forums. 

Then now i am faced with another issue its saying -
C:\Users\Work\Desktop\of_v0.8.4_win_cb_release\apps\myApps\crea_master\src\ofxCv.h Line9 fatal error: ofxCv/Utilities.h: No such file or directory.

This is probably a basic issue i should know and not waisting your time, but if you could help me out i would really appreciate that.

Thanks

**Comment by fabiaserra** [comment]
Hey Tobi! Thanks for explaining your issues here again.

This error you get now is something related only to the ofxCv addon. Make sure you can compile and run the examples that come with ofxCv. If you get the same error then you will probably have to post this same issue in the ofxCv issues forum https://github.com/kylemcdonald/ofxCv/issues :)

Thanks!
