### ISSUE TITLE
Getting Errors on compile

### ISSUE THREAD

**Issue by LeartZ** [fabiaserra/crea#21]
I'm very new to OF and Crea, so sorry if my issue is something very stupid.

I did all the steps as shown and also copied the ofxFlowTools and ofxUI from src of Crea, but I still get a lot of errors when compiling and it won't build at all.

Anyone can help?

Thanks a lot,
Leart
![error](https://cloud.githubusercontent.com/assets/16374551/11933793/4d2727f4-a7fe-11e5-9bf4-b28ea58a52e1.jpg)

**Comment by LeartZ** [comment]
Hmm... I think one of the problems was that I was using the latest OF release (0.9). So I got the 0.8, however now I'm getting over a 1000 errors.

I'll try with an older visual studio as well... but still... if there's anything else I should be looking up for, please let me know.

Thanks

**Comment by LeartZ** [comment]
Still the same issue... downloaded VS 2012 and tried everything I could!

**Comment by LeartZ** [comment]
and, on Code Blocks, I'm getting only 6 errors:

||=== Build: release in crea (compiler: GNU GCC Compiler) ===|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h||In function 'int ofxCv::getDepth(ofTexture&)':|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|45|error: 'class ofTextureData' has no member named 'glInternalFormat'|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h||In function 'int ofxCv::getChannels(ofTexture&)':|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|104|error: 'class ofTextureData' has no member named 'glInternalFormat'|
E:\Dokutech\Development\V8 CB\of_v0.8.4_win_cb_release\addons\ofxCv\libs\ofxCv\src\Calibration.cpp||In member function 'bool ofxCv::Calibration::calibrateFromDirectory(std::string)':|
E:\Dokutech\Development\V8 CB\of_v0.8.4_win_cb_release\addons\ofxCv\libs\ofxCv\src\Calibration.cpp|298|error: 'ofImage' has no member named 'load'|
E:\Dokutech\Development\V8 CB\of_v0.8.4_win_cb_release\addons\ofxCv\libs\ofxCv\src\Calibration.cpp||In member function 'void ofxCv::Calibration::draw(int) const':|
E:\Dokutech\Development\V8 CB\of_v0.8.4_win_cb_release\addons\ofxCv\libs\ofxCv\src\Calibration.cpp|385|error: 'ofDrawCircle' was not declared in this scope|
E:\Dokutech\Development\V8 CB\of_v0.8.4_win_cb_release\addons\ofxCv\libs\ofxCv\src\Calibration.cpp||In member function 'void ofxCv::Calibration::draw3d(int) const':|
E:\Dokutech\Development\V8 CB\of_v0.8.4_win_cb_release\addons\ofxCv\libs\ofxCv\src\Calibration.cpp|430|error: 'ofDrawCircle' was not declared in this scope|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h||In instantiation of 'cv::Mat ofxCv::toCv(ofBaseHasPixels_<T>&) [with T = unsigned char]':|
E:\Dokutech\Development\V8 CB\of_v0.8.4_win_cb_release\addons\ofxCv\libs\ofxCv\src\Calibration.cpp|299|required from here|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|235|error: no matching function for call to 'toCv(unsigned char_)'|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|235|note: candidates are:|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|230|note: cv::Mat ofxCv::toCv(cv::Mat&)|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|230|note:   no known conversion for argument 1 from 'unsigned char_' to 'cv::Mat&'|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|231|note: template<class T> cv::Mat ofxCv::toCv(ofPixels_<PixelType>&)|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|231|note:   template argument deduction/substitution failed:|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|235|note:   mismatched types 'ofPixels_<PixelType>' and 'unsigned char_'|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|234|note: template<class T> cv::Mat ofxCv::toCv(ofBaseHasPixels_<T>&)|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|234|note:   template argument deduction/substitution failed:|
......\addons\ofxCv\libs\ofxCv\include\ofxCv\Utilities.h|235|note:   mismatched types 'ofBaseHasPixels_<T>' and 'unsigned char_'|
||=== Build failed: 6 error(s), 2 warning(s) (0 minute(s), 2 second(s)) ===|

**Comment by ashwinv11** [comment]
I'm also having the same issue. I tried switching to the develop branch in ofxCv and that removed some errors, but I'm still having issues in irMarker.cpp

**Comment by mtslp** [comment]
seems that   No member named 'glInternalFormat' in 'ofTextureData' error comes from ofxCv . cant figure out whats wrong

**Comment by LeartZ** [comment]
Guys I somehow came to make it. But mainly just deleting/commenting where the issues showed up as they wheren't vital. Although that old Crea version cleared up most of the issues

**Comment by fabiaserra** [comment]
Hey guys, I have created a new branch and now the project should compile under OF 0.9.3: https://github.com/fabiaserra/crea/tree/OF0.9
