### ISSUE TITLE
Almost done

### ISSUE THREAD

**Issue by bboyslak** [fabiaserra/crea#22]
What can i do to make it work? Im trying and trying and no luck
<img width="1134" alt="screen shot 2016-02-26 at 12 50 12 pm" src="https://cloud.githubusercontent.com/assets/17500786/13360772/c50ac654-dc88-11e5-9a89-5e3d2ca7125b.png">

**Comment by bboyslak** [comment]
Now only im getting this error opencv2/opencv.hpp file not found

**Comment by robksawyer** [comment]
Made an example at https://github.com/robksawyer/crea-example that is compiling on El Capitan using Open Frameworks 0.9.3. Hope that helps a little.

However, I'm currently getting the following error and I'm not quite sure how to fix it.
`[ error ] ofPixels: image type not supported`

<img width="1104" alt="screen shot 2016-03-11 at 3 42 49 pm" src="https://cloud.githubusercontent.com/assets/179419/13718572/0bab4fd0-e7a0-11e5-8b94-089f98166ad5.png">

**Comment by gabbatv** [comment]
Hi Rob, thanks for the updated example ;)
I am trying this tool right now with my students here in Winchester. UK. having exactly the same issue - 
Any fixes??

**Comment by fabiaserra** [comment]
Hey guys, I have created a new branch and now the project should compile under OF 0.9.3: https://github.com/fabiaserra/crea/tree/OF0.9
