### ISSUE TITLE
 Build Error

### ISSUE THREAD

**Issue by Davidmarcell** [fabiaserra/crea#23]
Using Ofv.0.3 to build and getting these errors, any help?
![screen shot 2016-05-16 at 2 01 11 pm](https://cloud.githubusercontent.com/assets/4370458/15278614/08d4d526-1b6f-11e6-8e3b-73251e5aec75.png)

**Comment by fabiaserra** [comment]
I have created a new branch and now the project should compile under OF 0.9.3: https://github.com/fabiaserra/crea/tree/OF0.9

**Comment by gabbatv** [comment]
This new branch is working fine for me. 
Thank you for this update.. such a great example
