### ISSUE TITLE
Getting Errors on compile Visual Studio 2017 OF v0.9.8

### ISSUE THREAD

**Issue by GinesMendoza** [fabiaserra/crea#27]
I'm trying to install 'crea' on my computer but I can't build the project..., I followed all the step that the tutorial says....,Can  anyone can help? 
 
I'm using visual studio 2017 and the las version of OF, and I don't know if this can be the problem..
 
here the logs : 

![image](https://user-images.githubusercontent.com/9090336/31853195-f6e0fe78-b684-11e7-83c6-efdf676a67b0.png)

- **To solve the M_PI,  I included this to the header:**

`#define _USE_MATH_DEFINES`
`#include <cmath>`

![image](https://user-images.githubusercontent.com/9090336/31853267-126fca42-b686-11e7-96bf-d1b6a525c3b1.png)

included to the pages: **ParticleSystem** and **Particle**

- **To solve the getAverageFlow error,  I just comment the method but I don't know if I should do it because I don't know id this method is important or not...**

![image](https://user-images.githubusercontent.com/9090336/31853298-88a74cb2-b686-11e7-8a4a-008b6747edad.png)

if I try to return the value I get this error...

![image](https://user-images.githubusercontent.com/9090336/31853357-55d52128-b687-11e7-848c-33462fbdbdc6.png)

**Comment by pietrondo** [comment]
same problem in linux..
